export const products = [
    { id: 1, name: 'Product 1', description: 'Description of Product 1', price: 10.99 },
    { id: 2, name: 'Product 2', description: 'Description of Product 2', price: 19.99 },
    { id: 3, name: 'Product 3', description: 'Description of Product 3', price: 14.99 },
    { id: 4, name: 'Product 4', description: 'Description of Product 4', price: 8.99 },
    { id: 5, name: 'Product 5', description: 'Description of Product 5', price: 24.99 },
    { id: 6, name: 'Product 6', description: 'Description of Product 6', price: 16.99 },
    { id: 7, name: 'Product 7', description: 'Description of Product 7', price: 12.99 },
    { id: 8, name: 'Product 8', description: 'Description of Product 8', price: 21.99 },
    { id: 9, name: 'Product 9', description: 'Description of Product 9', price: 18.99 },
    { id: 10, name: 'Product 10', description: 'Description of Product 10', price: 13.99 },
    { id: 11, name: 'Product 11', description: 'Description of Product 11', price: 15.99 },
    { id: 12, name: 'Product 12', description: 'Description of Product 12', price: 9.99 },
    { id: 13, name: 'Product 13', description: 'Description of Product 13', price: 17.99 },
    { id: 14, name: 'Product 14', description: 'Description of Product 14', price: 22.99 },
    { id: 15, name: 'Product 15', description: 'Description of Product 15', price: 11.99 },
    { id: 16, name: 'Product 16', description: 'Description of Product 16', price: 20.99 },
    { id: 17, name: 'Product 17', description: 'Description of Product 17', price: 7.99 },
    { id: 18, name: 'Product 18', description: 'Description of Product 18', price: 23.99 },
    { id: 19, name: 'Product 19', description: 'Description of Product 19', price: 25.99 },
    { id: 20, name: 'Product 20', description: 'Description of Product 20', price: 10.49 }
];